### ISSUE TITLE
ModuleNotFoundError 

### ISSUE THREAD

**Issue by axerontios** [rossdargan/monzo-hass-sensor#9]
Hey Ross great work on this one, im trying to setup this sensor and followed the steps, the sensor load though it has not values and i could see the below errors on the logs :( 

HashIO version 93.2

sensor.monzoaccount | unknown | spend_today: null
-- | -- | --

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 220, in async_update_ha_state
    await self.async_device_update()
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 377, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/monzo/sensor.py", line 303, in update
    self.refresh_monzo_instance()
  File "/config/custom_components/monzo/sensor.py", line 237, in refresh_monzo_instance
    import monzo.monzo  # Import Monzo Class
**ModuleNotFoundError: No module named 'monzo'**

Found another version of the script at :
https://github.com/home-assistant/home-assistant/pull/17218
though it seems that never happened.

Thanks in advance for the help

cheers
Stelios

**Comment by rossdargan** [comment]
Hi

Sorry I didn't get notified of this issue. I can confirm the same thing is happening to me. I'll try and get a fix sorted.

Ta

Ross

**Comment by rossdargan** [comment]
Hi

This is fixed now. Note there are a few changes. monzo.py is now called sensor.py and must be in a folder called monzo. Also you need to include the manifest.json file.

Let me know if you have any issues!

I'm going to try and get it to be an official component now... wish me luck :)
